work on plugins page
teambit/bit-dev pull request #11
Opened 2021-10-07 15:30 UTC by JoshK2

2021-10-17 09:41 UTC, odedre requested changes

2021-10-17 09:41 UTC, odedre commented on community/ui/hero/hero.spec.tsx
> +//@TODO
?

2021-10-17 09:41 UTC, odedre commented on community/ui/pages/plugins/plugins.module.scss
> +  padding-bottom: 40px; // add a temporary space at the bottom of the page until we will have a footer.
better use margin instead of padding

2021-10-17 09:41 UTC, odedre commented on community/ui/pages/plugins/plugins.spec.tsx
> +it('should be in the document', () => {
I think we should wrap all the tests in a `describe`. it will make it easier to read when we run them

2021-10-17 09:41 UTC, odedre commented on community/ui/pages/plugins/plugins.tsx
> +import { devEnvsMock, compilingMock, testingMock, lintingFormatingMock, appsMock } from './plugins.mock';
we should pass the data as props from outside. that way we wont be coupled to using the mocks and can be easily replaced later

2021-10-17 09:41 UTC, odedre commented on community/ui/pages/plugins/plugins.tsx
> +        <PluginGroup title="Dev environments">
didnt we talk about using the aggregation category here?

2021-10-17 09:41 UTC, odedre commented on community/ui/plugins/create-section/bubble-graph.mock.ts
> +}
I really think we should find a better way to do this. it will be hard for eden to understand and maintain

2021-10-17 09:41 UTC, odedre commented on community/ui/plugins/create-section/create-section.docs.mdx
> +Create section for Plugins page on bit.dev website.
lets try to elaborate in the docs what it is that a component actually does. saying 'Create section' doesnt really mean anything

2021-10-17 09:41 UTC, odedre commented on community/ui/plugins/create-section/create-section.module.scss
> +@import '~@teambit/base-ui.layout.breakpoints/_breakpoints.scss';
I dont think we should be using this.
we should consider creating our own `breakpoints' component for the docs. lets consult @ranm8 about this

2021-10-17 09:41 UTC, odedre commented on community/ui/plugins/create-section/create-section.module.scss
> +  max-width: 1440px;
we have a `wideColumn` component that does this. can we use it instead?

2021-10-17 09:41 UTC, odedre commented on community/ui/plugins/create-section/create-section.module.scss
> +  margin: 40px auto;
I think this is also covered in the `wideColumn` component

2021-10-17 09:41 UTC, odedre commented on community/ui/plugins/create-section/create-section.module.scss
> +  grid-template-rows: repeat(9, 0.4fr);
I really dont like the `0.4fr` that we're using here and in the bubble graph. I think we can improve this

2021-10-17 09:41 UTC, odedre commented on community/ui/plugins/create-section/create-section.module.scss
> +    position: relative;
why do we need the `position: relative` ? cant we just `unset`?

2021-10-17 09:41 UTC, odedre commented on community/ui/plugins/explore-section/explore-section.docs.mdx
> +Explore section for Plugins page on bit.dev website.
again, lets elaborate

2021-10-17 09:41 UTC, odedre commented on community/ui/plugins/explore-section/explore-section.module.scss
> +  max-width: 1440px;
again, covered by `WideColumn`

2021-10-17 09:41 UTC, odedre commented on community/ui/plugins/explore-section/explore-section.module.scss
> +  margin: 40px 0;
also covered by WideColumn

2021-10-17 09:41 UTC, odedre commented on community/ui/plugins/explore-section/explore-section.module.scss
> +  grid-template-rows: repeat(5, 0.4fr);
lets try not to use `0.4fr`

2021-10-17 09:41 UTC, odedre commented on community/ui/plugins/explore-section/explore-section.module.scss
> +    .heading {
do we need `heading` and `subtitle` to be nested in `left`? we should try to have the css as flattened as possible to be able to override in the future

2021-10-17 09:41 UTC, odedre commented on design/ui/content/heading/heading.tsx
>     * a text to be rendered in the component.
when changing the props we should also make sure that the docs are up to date.
change `a text to be rendered in the component.` to `an element to be rendered in the heading`.

2021-10-17 09:44 UTC, odedre commented on workspace.jsonc
> +        "react-json-view": "1.21.3",
you added this just to use in the docs/compositions?

2021-10-17 10:14 UTC, JoshK2 commented on community/ui/graph/create-row/create-row.ts
> +};
This function do few things:
1. I want to decide the positions for each row easier.
2. I don't need IDs, and I don't want to write one for each icon.
3. I don't want to create a big Array like in `bubble-graph.mock.ts`.
4. I added the option to add spaces between bubbles easily, I use it for the bottom of the Plugins page.

2021-10-17 10:16 UTC, JoshK2 commented on community/ui/hero/hero.spec.tsx
> +//@TODO
We have a skip on this test because of an issue with something in the Graph, so I added a TODO to not forget to work on this issue.

2021-10-17 10:19 UTC, JoshK2 commented on community/ui/pages/plugins/plugins.module.scss
> +  padding-bottom: 40px; // add a temporary space at the bottom of the page until we will have a footer.
done

2021-10-17 12:08 UTC, JoshK2 commented on community/ui/pages/plugins/plugins.tsx
> +import { devEnvsMock, compilingMock, testingMock, lintingFormatingMock, appsMock } from './plugins.mock';
From outside is from `app.tsx`, the Plugins page is the only one to use these mocks.

2021-10-17 12:10 UTC, JoshK2 commented on community/ui/pages/plugins/plugins.tsx
> +        <PluginGroup title="Dev environments">
No

2021-10-17 12:22 UTC, JoshK2 commented on community/ui/plugins/create-section/create-section.module.scss
> +@import '~@teambit/base-ui.layout.breakpoints/_breakpoints.scss';
Ok, we can consult @ranm8 about it, but why do we need to create a new one if we already have one? The breakpoint should be the same across all our apps.

2021-10-17 12:35 UTC, JoshK2 commented on community/ui/plugins/create-section/create-section.module.scss
> +  max-width: 1440px;
We can, but this component have `width: calc(100% - 40px);` and it's not good for me because of the graph.
So the only thing I need from this component is the `max-width: 1440px;`, so I added it to the component instead of using another component just for this. Tell me what you think

2021-10-17 12:36 UTC, JoshK2 commented on community/ui/plugins/create-section/create-section.module.scss
> +  margin: 40px auto;
Yes, the margin left and right are auto in the `wideColumn`.
See what I wrote above and tell me what you think.

2021-10-17 12:38 UTC, JoshK2 commented on community/ui/plugins/create-section/create-section.module.scss
> +    position: relative;
You right, I changed it.
Done.

2021-10-17 12:40 UTC, JoshK2 commented on community/ui/plugins/explore-section/explore-section.docs.mdx
> +Explore section for Plugins page on bit.dev website.
done

2021-10-17 12:43 UTC, JoshK2 commented on community/ui/plugins/explore-section/explore-section.module.scss
> +  margin: 40px 0;
Same as I wrote upper.
If you think it's preferable to use the wide component and disable the width using css, I'll use it.

2021-10-17 12:47 UTC, JoshK2 commented on community/ui/plugins/explore-section/explore-section.module.scss
> +  grid-template-rows: repeat(5, 0.4fr);
So what to use instead? I use the exact same size as the grid-graph and hero.

2021-10-17 13:34 UTC, JoshK2 commented on design/ui/content/heading/heading.tsx
>     * a text to be rendered in the component.
done

2021-10-17 13:34 UTC, JoshK2 commented on workspace.jsonc
> +        "react-json-view": "1.21.3",
yes

2021-10-19 12:02 UTC, odedre commented on explorer/ui/gallery/component-card-group/component-card-group.docs.mdx
> +description: 'A group of components.'
A grid of component cards with an optional group title

2021-10-19 12:03 UTC, odedre commented on explorer/ui/gallery/component-card-group/component-card-group.docs.mdx
> +A components that renders a group of components with a title.
Renders a grid of component cards with an optional title above the group.

2021-10-19 12:04 UTC, odedre commented on explorer/ui/gallery/component-card-group/component-card-group.spec.tsx
> +  it('should have 4 component card', () => {
please add an 's' at the end

2021-10-19 12:07 UTC, odedre commented on explorer/ui/gallery/component-card-group/component-card-group.tsx
> +  title?: string;
I think we should add the option to pass `ReactNode` here too

2021-10-19 12:09 UTC, odedre commented on explorer/ui/search/search-input/search-input.tsx
> +export function SearchInput({ placeholder = 'Search', ...rest }: SearchInputProps) {
pass the icon from outside and have the search icon as a default. like with the placeholder

2021-10-19 12:10 UTC, odedre commented on workspace.jsonc
> +    "explorer/ui": {
did you check this with gilad?

2021-10-19 12:14 UTC, odedre commented on community/ui/hero/hero.spec.tsx
> +//@TODO
maybe add this description and add a `@josh` so we can know who should handle this

2021-10-19 12:20 UTC, odedre commented on community/ui/plugins/explore-section/explore-section.module.scss
> +  grid-template-rows: repeat(5, 0.4fr);
I know. its not ideal there too. lets try to find a better way with whole values

2021-10-19 12:24 UTC, odedre commented on workspace.jsonc
> +        "react-json-view": "1.21.3",
maybe we should add this option on bit's end. lets talk to ran about it

2021-10-19 13:26 UTC, JoshK2 commented on community/ui/hero/hero.spec.tsx
> +//@TODO
done

2021-10-19 14:57 UTC, JoshK2 commented on community/ui/plugins/explore-section/explore-section.tsx
> +  const onKeyUp = (event: React.KeyboardEvent<HTMLInputElement>) => {
You right, it's better.
Done

2021-10-19 15:08 UTC, JoshK2 commented on workspace.jsonc
> +    "explorer/ui": {
Yes, I'm waiting for his response.

2021-10-19 15:22 UTC, JoshK2 commented on community/ui/plugins/explore-section/explore-section.module.scss
> +  grid-template-rows: repeat(5, 0.4fr);
I use 1fr and it's good.

2021-10-19 16:04 UTC, odedre commented on community/ui/hero/hero.tsx
> +  teaser = 'Bit helps distribute to components and compose them into infinite features and apps. Forget monolithic apps and distribute to component-driven software. ',
consider putting the text in a const outside the function

2021-10-19 16:06 UTC, odedre commented on community/ui/pages/plugins/plugins.tsx
> +export function Plugins({ ...props }: PluginsProps) {
you dont need the spread here. just the one in the page

2021-10-19 16:08 UTC, odedre commented on explorer/ui/search/search-input/search-input.tsx
> +      onIconClick && onIconClick();
can we call it onSubmit instead of `onIconClick`?

2021-10-19 16:12 UTC, odedre commented on community/ui/plugins/plugin-group/index.ts
> +// Use Component Card Group component from explorer instead of this.
why not just delete the code?

2021-10-19 17:43 UTC, ranm8 commented on community/ui/plugins/plugin-group/index.ts
> +// Use Component Card Group component from explorer instead of this.
We can delete

2021-10-19 18:07 UTC, JoshK2 commented on community/ui/pages/plugins/plugins.tsx
> +export function Plugins({ ...props }: PluginsProps) {
I added the spread here just for the test, because I added `data-testid` attribute in the composition.

2021-10-19 18:54 UTC, JoshK2 commented on community/ui/plugins/plugin-group/index.ts
> +// Use Component Card Group component from explorer instead of this.
files removed

2021-10-19 19:01 UTC, merged