fixed most tasks
teambit/bit-dev pull request #313
Opened 2022-03-20 15:26 UTC by NitsanCohen770

most of the tasks done

2022-03-20 16:05 UTC, KutnerUri requested changes

2022-03-20 16:05 UTC, KutnerUri commented on bit/quick-start/learn-crossroad/learn-crossroad.module.scss
> +      width: 100px;
maybe just use relative size? `23%` or `10em`. This way you will not have to specify the size at each breakpoint
also, check the image dimensions above, the aspect ratio is different - 116x136 vs 100x100.
make sure the image is not distorted.

2022-03-20 16:05 UTC, KutnerUri commented on community/ui/hero/hero.module.scss
> +    color: #2b2b2b;
use tokens. ⚠️

2022-03-20 16:05 UTC, KutnerUri commented on design/ui/cards/card/card.tsx
> +export const Card = forwardRef<HTMLDivElement, CardProps>((props, ref) => {
give a name to the inner function. The convention is `CardWithRef` :(

2022-03-20 16:05 UTC, KutnerUri commented on design/ui/cards/card/card.tsx
> +      {props.children}
children are included in props, so you can skip them.

```suggestion
    <div ref={ref} className={classNames(styles.card, props.className)} {...props}/>
```

2022-03-21 09:39 UTC, KutnerUri commented on community/ui/hero/hero.module.scss
> +  }
```suggestion
  // @hack - override system tokens
  --bit-bg-dent: #0a1821;
  --bit-accent-color: #ededed;
  --bit-text-on-accent: #2b2b2b;
  color: #ededed;
  width: 20em;
  height: 48px;
```

2022-03-21 09:40 UTC, KutnerUri commented on community/ui/hero/hero.module.scss
> +  }
```suggestion
  --bit-bg-dent: #0a1821;
  --bit-accent-color: #ededed;
  --bit-text-on-accent: #2b2b2b;
  color: #ededed;
  width: 20em;
  height: 48px;
```
```

2022-03-21 09:47 UTC, KutnerUri requested changes

2022-03-21 09:47 UTC, KutnerUri commented on docs/blocks/sidebar/tree/tree.tsx
> +  }, []);
space line

2022-03-21 16:14 UTC, KutnerUri commented on bit/quick-start/card/card.mock.ts
> +    heading: 'Wiki',
STOP COMMITTING UNRELATED FILES

2022-03-21 16:14 UTC, KutnerUri commented on bit/quick-start/card/card.tsx
> +      cardRef?.current?.scrollIntoView({ behavior: 'smooth', block: 'center' });
unnecessary, remote

2022-03-21 16:14 UTC, KutnerUri commented on bit/quick-start/featured/featured.spec.tsx
> +    window.HTMLElement.prototype.scrollIntoView = jest.fn();
move to beforeEach, and remove during cleanup

2022-03-21 16:14 UTC, KutnerUri commented on community/ui/graph/component-card-graph/component-card-node.tsx
> +  // @ts-ignore TODO fix this
maybe just update componentUrl / component id? it should match the bit version

2022-03-22 10:01 UTC, KutnerUri approved these changes

2022-03-22 12:42 UTC, ranm8 commented on bit/content/what-is-bit/what-is-bit.module.scss
> +  }
@NitsanCohen770

2022-03-22 12:42 UTC, ranm8 commented on bit/content/what-is-bit/what-is-bit.module.scss
> +  }
@NitsanCohen770

2022-04-03 14:12 UTC, ranm8 commented
guys, can we get this PR done? @NitsanCohen770 @KutnerUri

2022-04-03 17:13 UTC, KutnerUri approved these changes

2022-04-03 17:13 UTC, KutnerUri commented on community/component-showcase/component-showcase.module.scss
> +  overflow-x: hidden;
add a comment explaining that this is for large previewed components

2022-04-03 17:13 UTC, KutnerUri commented on bit/content/what-is-bit/what-is-bit-qs.module.scss
> -.leftRight {
check this

2022-04-03 17:13 UTC, KutnerUri commented on bit/content/what-is-bit/what-is-bit-qs.module.scss
> -.leftRight {
also delete the file?

2022-04-03 18:38 UTC, merged