Fix/typos links
teambit/bit-dev pull request #348
Opened 2022-03-27 13:41 UTC by jonatankBIT

closed #347 
Several Links in the doc had been fixed across the following sections:

- Installation
- Compose
- Collaborate
- Update
- Workspace
- Components
- Dependencies
- Scope
- Envs
- Dev services

There are still sections to be reviewed (Apps, Packages, Frameworks, Extending bit, Config, Reference)

2022-03-27 16:39 UTC, ranm8 commented
You rock Jonathan! @giteden can you please review and merge!

2022-03-29 10:38 UTC, giteden approved these changes

2022-04-03 16:57 UTC, KutnerUri requested changes

2022-04-03 16:57 UTC, KutnerUri commented on workspace/content/workspace-link/workspace-link.mdx
> +Workspace Componnent Link are generated in the `node_modules` directory using `bit link`.
typo - the previous was correct. This is happening more than one, please check each place

2022-04-03 17:12 UTC, EllaStahl commented on docs/content/getting-started/create-workspace/create-workspace.mdx
> +├── node_modules --> includes external workspace modules and Workspace Componnent Link.
Please fix all "componnent" to "component" (I found 7 with search)

2022-04-03 21:03 UTC, NitsanCohen770 commented
@jonatankBIT there are a lot of conflicts
can you please resolve them asap?
we are moving bit.dev to lanes
thanks!

2022-04-04 07:02 UTC, jonatankBIT commented on workspace/content/workspace-link/workspace-link.mdx
> +Workspace Componnent Link are generated in the `node_modules` directory using `bit link`.
Fixed

2022-04-04 07:04 UTC, jonatankBIT commented on docs/content/getting-started/create-workspace/create-workspace.mdx
> +├── node_modules --> includes external workspace modules and Workspace Componnent Link.
Fixed, thanks!

2022-04-04 07:05 UTC, jonatankBIT commented
> @jonatankBIT there are a lot of conflicts can you please resolve them asap? we are moving bit.dev to lanes thanks!

working on that

2022-04-04 07:34 UTC, jonatankBIT commented
@KutnerUri @NitsanCohen770 @EllaStahl Updated requested changes.

2022-04-04 09:03 UTC, KutnerUri approved these changes

2022-04-04 09:03 UTC, KutnerUri commented on compilation/content/compiling-during-build/compiling-during-build.mdx
> +For type resolution in the Workspace we rely on the [Workspace Component Links](/workspace/structure/component-links) which symlinks the source code from within the link to the corresponding [Compone
@NitsanCohen770 
verify this type of links, I think they need to start with `/docs/...`

2022-04-04 09:03 UTC, merged