showcase code tab
teambit/bit-dev pull request #404
Opened 2022-04-11 13:44 UTC by odedre

- forked `code-tab-tree` and created a new component - `teambit.code/panels/file-tree`. - the main diff is that it gets its tree nodes from outside so we can replace any problematic links.
- created `teambit.code/code`, which is the code tab in the showcase. does everything except for resolve of the scope url.
- added `teambit.code/code` to component showcase.

2022-04-11 17:38 UTC, luvkapur commented on code/code/code.tsx
> +          height="90vh"
better to not use vh

2022-04-11 17:43 UTC, luvkapur commented on code/code/tree-node/tree-node.module.scss
> +    > div:first-child {
prefer to use specific classNames unless overriding external styles

2022-04-11 17:45 UTC, luvkapur commented on code/panels/file-tree/file-tree.module.scss
> +  > div:first-child {
prefer to use specific css classes

2022-04-11 17:46 UTC, luvkapur commented on code/panels/file-tree/file-tree.tsx
> +  const [openDrawerList, onToggleDrawer] = useState(['FILES' /* , 'DEPENDENCIES' */]);
clean up

2022-04-11 17:51 UTC, luvkapur approved these changes

2022-04-12 12:51 UTC, GiladShoham requested changes

2022-04-12 12:51 UTC, GiladShoham commented on workspace.jsonc
> +        "@teambit/graphql.contexts.graphql-provider": "0.0.7",
please use v0.0.8

2022-04-20 11:36 UTC, merged